name: my_library
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0
  retrofit: ">=4.0.0 <5.0.0"
  shared_preferences: ^2.2.2
  story: ^1.1.0

dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0'
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    

flutter_icons:
  ios: true
  android: true
  image_path: assets/images/main_icon.png